services:
- type: web
  name: internship-pipeline-api
  runtime: docker
  repo: https://github.com/Luke-Pitstick/internship-pipeline
  branch: main
  region: oregon
  plan: standard
  dockerfilePath: ./Dockerfile
  dockerContext: .
  autoDeployTrigger: checksPass
  healthCheckPath: /readyz
  disk:
    name: internship-pipeline-data
    mountPath: /var/data
    sizeGB: 5
  envVars:
  - key: PIPELINE_ORIGIN
    sync: false
  - key: PORT
    value: '8080'
