import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('owner claim, separate settings, logout and login work without profile or models', async ({page, request}) => {
  const token = JSON.parse(await readFile('test-results/setup.json', 'utf8')).token;
  expect((await request.get('/api/jobs')).status()).toBe(401);
  expect((await request.get('/api/resumes/private')).status()).toBe(401);
  await page.goto('/');
  await expect(page.getByRole('heading', {name: 'Make it yours.'})).toBeVisible();
  await expect(page.locator('form input')).toHaveCount(2);
  await expect(page.getByRole('button', {name: 'Create owner account'})).toBeDisabled();
  const requests: string[] = [];
  page.on('request', request => requests.push(request.url()));
  await page.goto('/#setup=invalid');
  await expect(page).toHaveURL(/\/$/);
  await expect(page.getByRole('button', {name: 'Create owner account'})).toBeDisabled();
  await page.goto(`/#setup=${token}`);
  await expect(page.getByRole('button', {name: 'Create owner account'})).toBeEnabled();
  await expect(page).toHaveURL(/\/$/);
  expect(await page.locator('body').innerText()).not.toContain(token);
  await page.screenshot({path:'test-results/owner-setup-desktop.png', fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/owner-setup-mobile.png', fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.reload();
  await expect(page.getByRole('button', {name: 'Create owner account'})).toBeEnabled();
  expect(requests.every(url => !url.includes(token))).toBe(true);

  await page.getByLabel('Username', {exact: true}).fill('synthetic-owner');
  await page.getByLabel('Password', {exact: true}).fill('synthetic-owner-password');
  await page.getByRole('button', {name: 'Create owner account'}).click();
  await expect(page.getByRole('heading', {name: 'Guided setup', exact: true})).toBeVisible();
  expect(await page.evaluate(() => sessionStorage.getItem('pipeline-setup'))).toBeNull();
  await expect(page.getByLabel('Defer model work and collect jobs first')).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', {name: 'Guided setup', exact: true})).toBeVisible();
  await page.getByRole('link', {name: 'Settings', exact: true}).click();
  await expect(page).toHaveURL(/\/settings\/$/);
  await expect(page.getByRole('heading', {name: 'Settings', exact: true})).toBeVisible();
  await page.getByRole('button', {name: 'AI Models', exact: true}).click();
  await expect(page.getByRole('heading', {name: 'AI Models', exact: true})).toBeFocused();
  await expect(page.getByText('Jev', {exact: true}).first()).toBeVisible();
  await page.setViewportSize({width: 390, height: 844});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({path: 'test-results/t03-settings-mobile.png', fullPage: true});
  await page.getByRole('button', {name: 'Log out'}).click();
  await expect(page.getByRole('heading', {name: 'Welcome back.'})).toBeVisible();
  await expect(page.getByLabel('Operator setup token')).toHaveCount(0);
  await page.getByLabel('Username', {exact: true}).fill('synthetic-owner');
  await page.getByLabel('Password', {exact: true}).fill('wrong-password');
  await page.getByRole('button', {name: 'Sign in', exact: true}).click();
  await expect(page.getByRole('alert')).toHaveText('Incorrect username or password');
  await page.getByLabel('Password', {exact: true}).fill('synthetic-owner-password');
  await page.getByRole('button', {name: 'Sign in', exact: true}).click();
  await expect(page.getByRole('heading', {name: 'Settings', exact: true})).toBeVisible();
  await page.goto('/');
  await expect(page.getByRole('heading', {name: 'Guided setup', exact: true})).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({width: 1440, height: 1000});
  await page.screenshot({path: 'test-results/t03-jobs-desktop.png', fullPage: true});
});
