import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
test('owner config, encrypted save, test worker, disable and mobile layout',async({page})=>{
  await page.goto('/settings/');
  await page.getByLabel('Operator setup token').fill(JSON.parse(await readFile('test-results-email/setup.json','utf8')).token);
  await page.getByLabel('Username',{exact:true}).fill('synthetic-email-owner');
  await page.getByLabel('Password',{exact:true}).fill('synthetic-email-password');
  await page.getByRole('button',{name:'Create owner account'}).click();
  await page.getByRole('button',{name:'Notifications & Integrations',exact:true}).click();
  await page.getByLabel('SMTP host').fill('smtp.example.test');
  await page.getByLabel('Username',{exact:true}).fill('synthetic-user');
  await page.getByLabel('Password',{exact:true}).fill('synthetic-secret');
  await page.getByLabel('Sender email').fill('sender@example.test');
  await page.getByLabel('Recipient email').fill('recipient@example.test');
  await page.getByLabel('Enable automatic email delivery').check();
  await page.getByLabel('Delivery mode').selectOption('digest');
  await page.getByLabel('Timezone',{exact:true}).fill('America/Denver');
  await page.getByRole('button',{name:'Save email settings'}).click();
  await expect(page.getByText('Email settings saved.',{exact:true})).toBeVisible();
  await expect(page.getByLabel('Password',{exact:true})).toHaveValue('');
  await page.getByRole('button',{name:'Send test email'}).click();
  await expect(page.getByText(/· accepted/)).toBeVisible({timeout:12000});
  await page.getByLabel('Enable automatic email delivery').uncheck();
  await page.getByRole('button',{name:'Save email settings'}).click();
  await expect.poll(async()=> (await(await page.request.get('/api/email')).json()).config.enabled).toBe(false);
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results-email/t14-mobile.png',fullPage:true});
});
