import {test, expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
test('off default, qualifying preview, automatic draft, persistent disable and manual action', async ({page}) => {
  await page.goto(`/settings/#setup=${JSON.parse(await readFile('test-results-generation-policy/setup.json','utf8')).token}`);

  await page.getByLabel('Username', {exact:true}).fill('synthetic-policy-owner');
  await page.getByLabel('Password', {exact:true}).fill('synthetic-policy-password');
  await page.getByRole('button', {name:'Create owner account'}).click();
  await expect(page.getByLabel('Name',{exact:true})).toBeVisible();
  await page.getByRole('button', {name:'Resume Generation',exact:true}).click();
  const toggle = page.getByLabel('Automatically generate qualifying drafts');
  await expect(toggle).not.toBeChecked();
  await expect(page.getByText('of 1 current open jobs qualify.',{exact:false})).toContainText('1');
  const job = JSON.parse(await readFile('test-results-generation-policy/job.json','utf8'));
  expect((await (await page.request.get(`/api/jobs/${job.id}/resume`)).json()).state).toBe('idle');
  await page.getByLabel('Minimum fit',{exact:true}).fill('100');
  await page.getByRole('button', {name:'Preview qualifying jobs'}).click();
  await expect(page.getByText('Preview updated for the rules shown below.')).toBeVisible();
  await toggle.check();
  await page.getByRole('button', {name:'Save generation rules'}).click();
  await expect(page.getByText('Generation rules saved. Manual generation remains available.')).toBeVisible();
  await page.reload();
  await page.getByRole('button', {name:'Resume Generation',exact:true}).click();
  await expect(toggle).toBeChecked();
  await expect.poll(async () => (await (await page.request.get(`/api/jobs/${job.id}/resume`)).json()).state,{timeout:20000}).toBe('draft');
  await toggle.uncheck();
  await page.getByRole('button', {name:'Save generation rules'}).click();
  await expect(page.getByText('Generation rules saved. Manual generation remains available.')).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({path:'test-results-generation-policy/t13-settings-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.goto(`/?selected=${job.id}`);
  await expect(page.getByText(/Draft awaiting your review/)).toBeVisible();
  await expect(page.getByRole('button', {name:'Generate job-specific résumé',exact:true})).toBeVisible();
  const draft = await (await page.request.get(`/api/jobs/${job.id}/resume`)).json();
  const pdf = await page.request.get(draft.download_url);
  expect((await pdf.body()).subarray(0,5).toString()).toBe('%PDF-');
});
