import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
test('saved searches persist backlog review budgets pause history and reconnect with real API worker',async({page})=>{
  await page.goto(`/settings/#setup=${JSON.parse(await readFile('test-results/search-setup.json','utf8')).token}`);

  await page.getByLabel('Username',{exact:true}).fill('synthetic-owner');
  await page.getByLabel('Password',{exact:true}).fill('synthetic-owner-password');
  await page.getByRole('button',{name:'Create owner account'}).click();
  await page.getByRole('button',{name:'Sources',exact:true}).click();
  await page.getByLabel('Search name',{exact:true}).fill('Synthetic Company');
  await page.getByLabel('Company board token').fill('example');
  await page.getByLabel('Daily run time').fill('09:00');
  await page.getByLabel('IANA timezone').fill('America/Denver');
  await page.getByRole('button',{name:'Save search',exact:true}).click();
  await page.getByRole('button',{name:'Run now',exact:true}).click();
  await expect(page.getByText('2 backlog jobs await explicit review.')).toBeVisible({timeout:15000});
  await expect(page.getByText(/2 collected · 0 evaluated/)).toBeVisible();
  await page.getByRole('button',{name:'Review backlog',exact:true}).click();
  await expect(page.getByText(/2 collected · 2 evaluated/)).toBeVisible({timeout:15000});
  await page.reload();await page.getByRole('button',{name:'Sources',exact:true}).click();
  await expect(page.getByText(/2 collected · 2 evaluated/)).toBeVisible();
  await page.getByRole('button',{name:'Pause Synthetic Company',exact:true}).click();
  await expect(page.getByRole('button',{name:'Run now',exact:true})).toBeDisabled();
  await page.getByRole('button',{name:'Resume Synthetic Company',exact:true}).click();
  await page.getByRole('button',{name:'Run now',exact:true}).click();
  await expect(page.getByText(/2 collected · 2 evaluated/)).toBeVisible({timeout:15000});
  await page.getByRole('button',{name:'Cancel remaining run work'}).click();
  await expect(page.getByText('Run status: cancelled.')).toBeVisible();
  await page.getByLabel('Search name',{exact:true}).fill('Broken source');
  await page.getByLabel('Company board token').fill('brokenboard');
  await page.getByRole('button',{name:'Save search',exact:true}).click();
  await page.getByRole('region',{name:'Broken source',exact:true}).getByRole('button',{name:'Run now'}).click();
  await expect(page.getByText(/Source error: source_request_failed/)).toBeVisible({timeout:15000});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/t08-search-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Diagnostics',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Source freshness',exact:true})).toBeVisible();
  await expect(page.getByText(/Supervisor heartbeat unavailable/)).toBeVisible();
  await expect(page.getByText(/work_failed_check_settings/).first()).toBeVisible();
  expect(await page.locator('body').textContent()).not.toContain('synthetic-secret-token');
  await page.getByRole('button',{name:/Retry task/}).first().click();
  await expect(page.getByRole('button',{name:/Retry task/})).toHaveCount(0);
  await page.goto('/');await page.getByText('Run history',{exact:true}).click();
  await expect(page.getByText(/Synthetic Company · cancelled/)).toBeVisible();
});
