import {test, expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';

test('fresh browser setup resumes imported facts, models, skips, failed source correction and useful jobs',async({page})=>{
  test.setTimeout(90000);
  await page.goto(`/#setup=${JSON.parse(await readFile('test-results-setup/setup.json','utf8')).token}`);

  await page.getByLabel('Username',{exact:true}).fill('synthetic-owner');
  await page.getByLabel('Password',{exact:true}).fill('synthetic-owner-password');
  await page.getByRole('button',{name:'Create owner account'}).click();
  await expect(page).toHaveURL(/\/setup\//);
  const jev = page.locator('form').filter({has:page.getByRole('heading',{name:'Jev',exact:true})});
  await jev.getByLabel(/^API key/).fill('synthetic-invalid');
  await jev.getByRole('button',{name:'Save Jev',exact:true}).click();
  await jev.getByRole('button',{name:'Test Jev',exact:true}).click();
  await expect(page.getByRole('alert').filter({hasText:/credential|authentication|rejected/i})).toBeVisible();
  await page.getByLabel('Defer model work and collect jobs first').check();
  await page.getByRole('button',{name:'Save progress and continue'}).click();
  await page.getByLabel('Resume document').setInputFiles('tests/fixtures/resume.synthetic.docx');
  await page.getByRole('button',{name:'Upload and review'}).click();
  await page.getByRole('button',{name:'Preview profile changes'}).click();
  await page.getByLabel('I reviewed the selected claims against the source and confirm the profile changes.').check();
  await page.getByRole('button',{name:'Confirm and save imported profile'}).click();
  await expect(page.getByLabel('Name',{exact:true})).toHaveValue('Synthetic Candidate');
  await page.reload();
  await expect(page.getByLabel('Name',{exact:true})).toHaveValue('Synthetic Candidate');
  await page.getByRole('button',{name:'Save progress and continue'}).click();
  await expect(page.getByRole('heading',{name:'Job filters',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Save progress and continue'}).click();
  await page.getByLabel('Search name',{exact:true}).fill('Synthetic first search');
  await page.getByLabel('Company board token').fill('brokenboard');
  await page.getByRole('button',{name:'Save search',exact:true}).click();
  await expect(page.getByRole('status').filter({hasText:'Search saved.'})).toBeVisible();
  await expect(page.getByRole('button',{name:'Run now'})).toHaveCount(0);
  await page.getByRole('button',{name:'Save progress and continue'}).click();
  await page.getByLabel('Email during setup').selectOption('connect');
  await page.getByLabel('SMTP host').fill('smtp.example.test');
  await page.getByLabel('Username',{exact:true}).fill('synthetic');
  await page.getByLabel('Password',{exact:true}).fill('synthetic-smtp-secret');
  await page.getByLabel('Sender email').fill('from@example.test');
  await page.getByLabel('Recipient email').fill('to@example.test');
  await page.getByRole('button',{name:'Save email settings'}).click();
  await page.getByRole('button',{name:'Send test email'}).click();
  await expect(page.getByText(/failed.*credential_unavailable|failed/i).first()).toBeVisible({timeout:12000});
  await page.getByRole('button',{name:'Save progress and continue'}).click();
  await expect(page.getByRole('button',{name:'Confirm configuration and run first search'})).toBeDisabled();
  await page.getByRole('link',{name:'Correct integrations'}).click();
  await expect(page.getByRole('heading',{name:'Notifications & Integrations',exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Return to guided setup'}).click();
  await page.getByRole('button',{name:'5. Optional integrations',exact:false}).click();
  await page.getByLabel('Email during setup').selectOption('skip');
  await page.getByLabel('Sheets during setup').selectOption('skip');
  await page.getByRole('button',{name:'Save progress and continue'}).click();
  await expect(page.getByText(/Email: skip · failed/)).toBeVisible();
  await page.getByRole('link',{name:'Correct model connections'}).click();
  await expect(page.getByRole('heading',{name:'AI Models',exact:true})).toBeVisible();
  await jev.getByLabel(/^API key/).fill('synthetic-valid');
  await jev.getByRole('button',{name:'Save Jev',exact:true}).click();
  await jev.getByRole('button',{name:'Test Jev',exact:true}).click();
  await expect(jev.getByText('Capability test passed',{exact:true})).toBeVisible();
  const general=page.locator('form').filter({has:page.getByRole('heading',{name:'General LLM',exact:true})});
  await general.getByLabel('Model',{exact:true}).fill('test-model');
  await general.getByLabel(/^API key/).fill('synthetic-general-valid');
  await general.getByRole('button',{name:'Save General LLM',exact:true}).click();
  await general.getByRole('button',{name:'Test General LLM',exact:true}).click();
  await expect(general.getByText('Capability test passed',{exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Return to guided setup'}).click();
  await page.getByRole('button',{name:'1. Models',exact:false}).click();
  await page.getByLabel('Defer model work and collect jobs first').uncheck();
  await page.getByRole('button',{name:'Save progress and continue'}).click();
  await page.getByRole('button',{name:'6. Configuration preview',exact:false}).click();
  await page.getByRole('button',{name:'Confirm configuration and run first search'}).click();
  await expect(page.getByRole('link',{name:'Correct source connection'})).toBeVisible({timeout:15000});
  await page.reload();
  await expect(page.getByRole('link',{name:'Correct source connection'})).toBeVisible();
  await page.getByRole('link',{name:'Correct source connection'}).click();
  await expect(page.getByRole('heading',{name:'Sources',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Edit Synthetic first search'}).click();
  await page.getByLabel('Company board token').fill('example');
  await page.getByRole('button',{name:'Save search',exact:true}).click();
  await expect(page.getByRole('status').filter({hasText:'Search saved.'})).toBeVisible();
  await page.getByRole('link',{name:'Return to guided setup'}).click();
  await page.getByRole('button',{name:'Return to configuration preview'}).click();
  await expect(page.getByText(/greenhouse · example/)).toBeVisible();
  await page.getByRole('button',{name:'Confirm configuration and run first search'}).click();
  await expect(page.getByRole('button',{name:'Finish setup and view jobs'})).toBeVisible({timeout:15000});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results-setup/t16-setup-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Finish setup and view jobs'}).click();
  await expect(page).toHaveURL(/\/(?:\?.*)?$/);
  await expect(page.getByText('Synthetic Python internship',{exact:true}).first()).toBeVisible();
  await page.reload();
  await expect(page).toHaveURL(/\/(?:\?.*)?$/);
  const state=await (await page.request.get('/api/onboarding')).json();
  expect(state.complete).toBe(true);expect(state.email).toBe('skip');expect(state.sheets).toBe('skip');
  const jobs=await (await page.request.get('/api/jobs')).json();
  expect(JSON.stringify(jobs)).not.toContain('synthetic-smtp-secret');
});
