import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
test('Google setup/tab selection, preview, real queue and explicit inward review',async({page})=>{
  const setup=JSON.parse(await readFile('test-results-sheets/setup.json','utf8'));
  await page.goto('/settings/');
  await page.getByLabel('Operator setup token').fill(setup.token);
  await page.getByLabel('Username',{exact:true}).fill('synthetic-sheets-owner');
  await page.getByLabel('Password',{exact:true}).fill('synthetic-sheets-password');
  await page.getByRole('button',{name:'Create owner account'}).click();
  await page.getByRole('button',{name:'Notifications & Integrations',exact:true}).click();
  await page.getByLabel('Spreadsheet ID',{exact:true}).fill('synthetic-sheet-id');
  await page.getByLabel('Google service-account JSON key',{exact:true}).fill(setup.service_account);
  await page.getByRole('button',{name:'Save Sheets connection'}).click();
  await expect(page.getByText('Sheets connection saved. Test current access before previewing.',{exact:true})).toBeVisible();
  await expect(page.getByLabel('Google service-account JSON key')).toHaveValue('');
  await page.getByRole('button',{name:'Test spreadsheet access'}).click();
  await expect(page.getByText('Selected spreadsheet: Synthetic Opportunities')).toBeVisible();
  await page.getByLabel('Destination tab').selectOption('Jobs');
  await page.getByLabel('Inward notes column').selectOption('K');
  await page.getByLabel('Inward application status column').selectOption('M');
  await page.getByRole('button',{name:'Save Sheets connection'}).click();
  await expect.poll(async()=> (await(await page.request.get('/api/sheets')).json()).revision).toBe(2);
  await page.getByRole('button',{name:'Test spreadsheet access'}).click();
  await page.getByRole('button',{name:'Preview spreadsheet sync'}).click();
  await expect(page.getByRole('heading',{name:'Dry-run preview'})).toBeVisible();
  await expect(page.getByText('=UNTRUSTED()',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Sync previewed records'}).click();
  await expect(page.getByText('complete',{exact:true})).toBeVisible({timeout:12000});
  await expect(page.getByRole('button',{name:'Accept spreadsheet change'})).toHaveCount(2);
  const before=await(await page.request.get(`/api/jobs/${setup.job_id}`)).json();
  expect(before.application_status).not.toBe('applied');
  await page.getByRole('button',{name:'Accept spreadsheet change'}).first().click();
  await expect(page.getByRole('button',{name:'Accept spreadsheet change'})).toHaveCount(1);
  await page.getByRole('button',{name:'Accept spreadsheet change'}).click();
  await expect(page.getByText('No inward changes need review.')).toBeVisible();
  const csv=await page.request.get('/api/sheets/export.csv');
  expect(await csv.text()).toContain("'=UNTRUSTED()");
  expect(await csv.text()).toContain('Synthetic manual note');
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results-sheets/t15-mobile.png',fullPage:true});
});
