import {test, expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
test('configured model draft, inspect facts, preview, download and explicit review without destinations', async ({page}) => {
  await page.goto('/settings/');
  await page.getByLabel('Operator setup token').fill(JSON.parse(await readFile('test-results-tailored/setup.json','utf8')).token);
  await page.getByLabel('Username', {exact:true}).fill('synthetic-tailored-owner');
  await page.getByLabel('Password', {exact:true}).fill('synthetic-tailored-password');
  await page.getByRole('button', {name:'Create owner account'}).click();
  await expect(page.getByLabel('Name',{exact:true})).toBeVisible();
  const job = JSON.parse(await readFile('test-results-tailored/job.json','utf8'));
  await page.goto(`/?selected=${job.id}`);
  await page.getByRole('button', {name:'Generate job-specific résumé',exact:true}).click();
  await expect(page.getByText(/Draft awaiting your review/)).toBeVisible({timeout:20000});
  await page.getByText('Inspect selected and omitted facts').click();
  await expect(page.getByText(/Built a Python API serving 120/)).toBeVisible();
  await expect(page.getByText(/Developed an accessible dashboard/)).toBeVisible();
  const state = await (await page.request.get(`/api/jobs/${job.id}/resume`)).json();
  await page.getByRole('button', {name:'Preview PDF',exact:true}).click();
  await expect(page.getByTitle('Job-specific résumé PDF preview')).toHaveAttribute('src',state.preview_url);
  const pdf = await page.request.get(state.preview_url);
  expect(pdf.headers()['content-disposition']).toContain('inline');
  expect((await pdf.body()).subarray(0,5).toString()).toBe('%PDF-');
  await expect.poll(() => page.frames().map(f=>f.url()).join(' ')).toContain('chrome-extension://');
  const viewer = page.frames().find(f=>f.url().startsWith('chrome-extension://'))!;
  await expect.poll(()=>viewer.evaluate(()=>(document.querySelector('pdf-viewer') as HTMLElement & {initialLoadComplete_:boolean})?.initialLoadComplete_)).toBe(true);
  const event = page.waitForEvent('download');
  await page.getByRole('link',{name:'Download draft PDF'}).click();
  await (await event).saveAs('test-results-tailored/t12-tailored-browser.pdf');
  await page.getByRole('button',{name:'I reviewed this draft and its omissions'}).click();
  await expect(page.getByText(/Review recorded/)).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({path:'test-results-tailored/t12-mobile.png',fullPage:true});
});
